### ISSUE TITLE
Use Case Diagram Feedback

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-cybertech#3]
https://github.com/PUP-BSIT/project-cybertech/blob/c4a9916afb902c21f4fcbf0e0e608d0dc9db127d/documents/logistic_diagrams.pdf
- Update "Logistic User Case Diagram" to "Logistics Use Case Diagram". Please also indicate page numbers so we can communicate better.
- get-delivery-history should be replaced with "Display Delivery History".
- Remove arrow connection between "Select Delivery Partner" and "get-delivery".
- Remove arrow connection between "Display list of delivery" and "get-delivery".
- get-delivery should be replaced with "Display List of Deliveries assigned to Delivery Partner".
- "Delivery Process" should be replace with "Update Delivery".
- You don't need to distinguish users inside and outside your scope. Just create one box.
- Put all users outside the box. Only the actions are inside the box.

**Comment by malaluankylarica** [comment]
Thank you Sir for sharing your feedback. We recognize these concerns and are presently focused on resolving all raised issues.
